namespace CC_Library.Datatypes
{
    public enum Datatype
    {
        None,
        Dictionary,
        Alpha,
        AlphaContextPrimary,
        AlphaContextSecondary,
        AlphaContextTertiary,
        Masterformat,
        OccupantLoadFactor,
        StudLayer,
        OccupancyGroup,
        ObjectStyle,
        ObjectCategory,
        Subcategory,
        CutLineWeight,
        ProjectedLineWeight,
        CutLinePattern,
        ProjectedLinePattern,
        CategoryVisibility,
        RoomPrivacy,
        Stonk,
        StonkContext,
        MaxValue,
        MinValue,
        AAPL
    }
}
