namespace CC_Library
{
    public enum OccLoadFactor
    {
        A5,
        A7,
        A11,
        A15,
        A20,
        A30,
        A35,
        A40,
        A50,
        A60,
        A100,
        A120,
        A150,
        A200,
        A240,
        A300,
        A500
    }
    public enum OccGroup
    {
        A1,
        A2,
        A3,
        A4,
        A5,
        B,
        E,
        F1,
        F2,
        H1,
        H2,
        H3,
        H4,
        H5,
        I1,
        I2,
        I3,
        R1,
        R2,
        R3,
        R4,
        S1,
        S2,
        U,
        L,
        C
    }
    public enum ObjectCategory
    {
    //Door and Window
        Swing,
        Frame,
        Head,
        Jamb,
        Sill,
        Panel,
        Glazing,
    //Cabinetry
        Box,
        Outline,
        Counter,
        Base,
        Pull,
        Details,
    //Details
        Fasteners,
        Blocking,
        Structure,
        Det_Beyond,
        Det_03_XFine,
        Det_03_XFine_Dash,
        Det_04_Fine,
        Det_04_Fine_Dash,
        Det_05_Medium,
        Det_05_Medium_Dash,
        Det_06_Heavy,
        Det_06_Heavy_Dash
    }
}
